Artique/urls.py
from django.contrib import admin
from django.urls import path
from ArtiqueApp import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('^accounts/login/', admin.site.urls),

    path('ahome/', views.ahome,name='ahome'),
    path('artiquehome/', views.artiquehome,name='artiquehome'),
    path('appointment/', views.appointment,name='appointment'),
    path('contactus/', views.contactus,name='contactus'),
    path('confirmation/', views.confirmation,name='confirmation'),
    path('confirmappoint/', views.confirmappoint,name='confirmappoint'),    
    path('myactivities/', views.myactivities,name='myactivities'),    
    path('ourcollection/<int:prd_pk>', views.ourcollection,name='ourcollection'),
    path('srchourcollection/<str:cnt>', views.srchourcollection,name='srchourcollection'),
    path('delcart/<int:ord_pk>', views.delcart,name='delcart'),
    path('delcart1/<int:ord_pk>', views.delcart1,name='delcart1'),
    path('delivered/<int:ord_pk>', views.delivered,name='delivered'),
    path('cancelled/<int:ord_pk>', views.cancelled,name='cancelled'),
    path('mycart/<int:prod_pk>', views.mycart,name='mycart'),
    path('gallery/', views.gallery,name='gallery'),
    path('signupuser/', views.signupuser,name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('loginuser/', views.loginuser,name='loginuser'),
    path('logoutuser/', views.logoutuser,name='logoutuser'),
    path('confirmsubscribe/', views.confirmsubscribe,name='confirmsubscribe'),
    path('OrderList/', views.OrderList,name='OrderList'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ArtiqueApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

class Product_Type(models.Model):
    name = models.CharField(max_length=50)
    Description = models.CharField(max_length=300)
    Is_Active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Products(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    Previous_Rate = models.DecimalField(max_digits=5, decimal_places=2,blank=True)
    Current_Rate = models.DecimalField(max_digits=5, decimal_places=2)
    Main_img = models.ImageField(upload_to='ArtiqueApp/static/images/')
    img1 = models.ImageField(upload_to='ArtiqueApp/static/images/',blank=True)
    img2 = models.ImageField(upload_to='ArtiqueApp/static/images/',blank=True)
    Display_main = models.BooleanField(default=False)
    Product_Type = models.ForeignKey(Product_Type, on_delete=models.CASCADE,default=1)
    Product_code = models.CharField(max_length=100,blank=True)

    def __str__(self):
        return self.title
    
class Transact_hdr(models.Model):
    StatusType = models.TextChoices('StatusType', 'Pending InProgress Completed Cancelled')
    Status = models.CharField(max_length=500, choices=StatusType.choices)
    Mobile = models.CharField(max_length=500, blank=True)
    Comments  = models.TextField(blank=True)
    Created = models.DateTimeField(auto_now_add=True)
    Datecompleted = models.DateTimeField(null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Amount = models.DecimalField(max_digits=5, decimal_places=2,blank=True,default=0)
    Order_date = models.DateTimeField(default=now, blank=True)
   

class Transact_dtl(models.Model):
    Transact_id = models.ForeignKey(Transact_hdr, on_delete=models.CASCADE,default=1)
    Product = models.ForeignKey(Products, on_delete=models.CASCADE,default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Created = models.DateTimeField(auto_now_add=True)
    Current_Rate = models.DecimalField(max_digits=5, decimal_places=2,default=0)
    

class Appointment(models.Model):
    name = models.CharField(max_length=500)
    mobile = models.CharField(max_length=500)
    emailid = models.CharField(max_length=500)
    dt = models.DateField(auto_now=False)
    typ = models.CharField(max_length=500)
    visit_time = models.CharField(max_length=500)
    msg = models.TextField(max_length=1000, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name + "-" + str(self.dt)

class subscriber(models.Model):
    name = models.CharField(max_length=500)
    emailid = models.CharField(max_length=500)
    send_info = models.BooleanField()
    mobile = models.CharField(max_length=500,null= True)
    
    def __str__(self):
        return self.emailid

ArtiqueApp/forms.py
from django.forms import ModelForm
from .models import Appointment,subscriber


class AppointForm(ModelForm):
     class Meta:
        model = Appointment
        fields = ['name', 'mobile', 'emailid','dt','typ','visit_time','msg']

class SubscribeForm(ModelForm):
     class Meta:
        model = subscriber
        fields = ['name', 'emailid','send_info','mobile']        

ArtiqueApp/views.py
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError, connection, transaction
from django.contrib.auth import login,logout,authenticate
from django.db.models import Sum
from django.template.loader import render_to_string
from .models import Products, Product_Type, Transact_hdr, Transact_dtl, Appointment,subscriber
from .forms import AppointForm, SubscribeForm
from decimal import Decimal
from django.core.mail import send_mail
from pathlib import Path
from email.mime.image import MIMEImage
from django.core.mail import EmailMultiAlternatives
from django.http import Http404
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models import Q 
from django.contrib.admin.views.decorators import staff_member_required
from datetime import date

def signupuser(request):

    if request.method == 'GET':
        return render(request,'Signupuser.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                if request.POST['email'] and request.POST['last_name']:
                    usr = User.objects.create_user(username=request.POST['username'],password=request.POST['password1'],first_name=request.POST['first_name'],last_name=request.POST['last_name'],email=request.POST['email'])
                    usr.save()
                    login(request,usr)

                    
                    return redirect('artiquehome')    
                else:
                    return render(request,'Signupuser.html', { 'error': 'Please enter Email Id and Mobile No.'})
                
            except IntegrityError:
                return render(request,'Signupuser.html', {'form': UserCreationForm(), 'error': 'Username exists'})
        else:
            return render(request,'Signupuser.html', {'form': UserCreationForm(), 'error': 'Password doesnt match'})

def artiquehome(request):
    prdtyp = Product_Type.objects.all()
    prod = Products.objects.filter(Display_main=True).order_by('-id')[:4]
    return render(request,'Bootstrap.html',{'prodtyp':prdtyp,'products': prod })

@login_required
def placeorder(request):
    return redirect('artiquehome')

@login_required
def myactivities(request):
    prdtyp = Product_Type.objects.all()
    Trans_hdr = Transact_hdr.objects.filter(user=request.user).order_by('-id')
    Trans = Transact_dtl.objects.filter(user=request.user).order_by('-id')
    Appnt = Appointment.objects.filter(user=request.user).order_by('-dt')
    return render(request,'myactivities.html', {'prodtyp':prdtyp,'CartH': Trans_hdr, 'Appnt': Appnt})

def ahome(request):
    
    prdtyp = Product_Type.objects.all()
    prod = Products.objects.filter(Display_main=True).order_by('-id')[:4]
    return render(request,'Home.html',{'prodtyp':prdtyp,'products': prod})

@staff_member_required
def OrderList(request):
    
    prdtyp = Product_Type.objects.all()
    Trans_hdr = Transact_hdr.objects.filter(~Q(Status = 'Pending')).order_by('-id')
    Appn = Appointment.objects.all().order_by('-dt')
    today =  date.today()
    return render(request,'OrderList.html',{'prodtyp':prdtyp,'Cart': Trans_hdr, 'Appn': Appn,'today': today})


def contactus(request):
    prdtyp = Product_Type.objects.all()
    if request.method == 'POST':
        form = SubscribeForm(request.POST)  
        form.save()
        return redirect('artiquehome')  
    else:
        return render(request,'ContactUs.html',{'prodtyp':prdtyp, 'form':SubscribeForm()})

def ourcollection(request,prd_pk):
    prdtyp = Product_Type.objects.all()
    prd = Products.objects.filter(Product_Type=prd_pk)
    return render(request,'Collections.html',{'products':prd , 'prodtyp':prdtyp})

def confirmsubscribe(request):    
    if request.method == 'POST':
        form = SubscribeForm(request.POST)  
        form.save()
        return redirect('artiquehome')        
    else:
        return redirect('artiquehome')        

@login_required
def appointment(request):
    prdtyp = Product_Type.objects.all()
    usr= request.user
    ap_name = usr.first_name
    ap_email = usr.email
    ap_mob = usr.last_name
    return render(request,'Appointment.html',{'prodtyp':prdtyp,'ap_name':ap_name,'ap_email':ap_email,'ap_mob':ap_mob, 'form':AppointForm() })
    
@login_required    
def confirmappoint(request):
    if request.method == 'POST':
        form = AppointForm(request.POST)  
        obj = form.save(commit=False)
        obj.user = request.user
        obj.save()

        subject = 'Your Appointment is confirmed...'
        
        usr= request.user
        ap_email = usr.email       

        from_email = settings.EMAIL_HOST_USER
        to_list = [settings.EMAIL_HOST_USER,ap_email]

        #image_path = 'C:\Python\Artique\ArtiqueApp\static\images\Artique.jpg'
        image_path = settings.MEDIA_ROOT + '\ArtiqueApp\static\images\Artique.jpg'
        image_path1 = settings.MEDIA_ROOT + '\ArtiqueApp\static\images\Art_Attach.jpg'
        image_name = Path(image_path).name
        image_name1 = Path(image_path1).name
        
            
        msg_plain = render_to_string('email.txt', { 'appn':obj })
        msg_html = render_to_string('email.html', { 'appn':obj })

        #I used EmailMultiAlternatives because I wanted to send both text and html
       
        emailMessage = EmailMultiAlternatives(subject=subject, body=msg_plain, from_email=from_email, to=to_list)
        emailMessage.attach_alternative(msg_html, "text/html")
        emailMessage.content_subtype = 'html'
        emailMessage.mixed_subtype = 'related'

        image_file = open(image_path, 'rb')
        msg_image = MIMEImage(image_file.read())
        image_file.close()
        msg_image.add_header('Content-ID', '<image1>')
        emailMessage.attach(msg_image)
       
        image_file1 = open(image_path1, 'rb')
        msg_image1 = MIMEImage(image_file1.read())
        image_file1.close()
        msg_image1.add_header('Content-ID', '<image2>')
        emailMessage.attach(msg_image1)
       

        emailMessage.send(fail_silently=False)
        return redirect('myactivities')
        
    else:
        return redirect('placeorder')

def srchourcollection(request,cnt):
    prdtyp = Product_Type.objects.all()
    prd = Products.objects.all()

    

    if request.method == 'GET':
        return render(request,'Collections.html',{'products':prd , 'prodtyp':prdtyp})
    else:
        if cnt == '0':
            prd = Products.objects.all()
        else:
            prd = Products.objects.filter(description__icontains=request.POST['search'])

        return render(request,'Collections.html',{'products':prd , 'prodtyp':prdtyp})    
    

@login_required
def delcart(request, ord_pk):
    prd = Products.objects.filter(Product_Type=ord_pk)
    prdtyp = Product_Type.objects.all()
    if request.method == 'POST':
        try:
            try:
                prdtrn = Transact_hdr.objects.get(Status='Pending',user=request.user)
                cart_id = prdtrn.id
            except Transact_hdr.DoesNotExist:
                return render(request,'nocart.html',{'prodtyp': prdtyp})

            Tran_del = Transact_dtl.objects.get(pk=ord_pk)
            Tran_del.delete()
            
            cart = Transact_dtl.objects.filter(Transact_id=prdtrn)
            total_price = Transact_dtl.objects.filter(Transact_id=prdtrn).aggregate(Sum('Current_Rate'))

            return render(request,'mycart.html',{'Cart': cart , 'CartId': cart_id , 'prodtyp':prdtyp, 'Totalprice': total_price })
        except IntegrityError:
                return render(request,'Collections.html',{'products':ord_pk , 'prodtyp':prdtyp, 'error': 'Some error'})

@staff_member_required
def delcart1(request, ord_pk):
    prd = Products.objects.filter(Product_Type=ord_pk)
    prdtyp = Product_Type.objects.all()
    if request.method == 'POST':
        try:
            Tran_del = Transact_dtl.objects.get(pk=ord_pk)
            prdtrn = Tran_del.Transact_id 
            Tran_del.delete()

            total_price = Transact_dtl.objects.filter(Transact_id=prdtrn).aggregate(Sum('Current_Rate'))
            decimal_val = float(total_price['Current_Rate__sum'])    
            prdtrn.Amount = decimal_val
            prdtrn.save()
                        
            return redirect('OrderList')  
        except IntegrityError:
                return redirect('OrderList')  

@login_required
def confirmation(request):
    prdtyp = Product_Type.objects.all()
    if request.method == 'POST':
        try:
            prdtrn = Transact_hdr.objects.get(Status='Pending',user=request.user)
            cart_id = prdtrn.id
        except Transact_hdr.DoesNotExist:
            return render(request,'nocart.html',{'prodtyp': prdtyp})

        total_price = Transact_dtl.objects.filter(Transact_id=prdtrn).aggregate(Sum('Current_Rate'))
        decimal_val = float(total_price['Current_Rate__sum'])    
        prdtrn.Amount = decimal_val
        prdtrn.Mobile = request.POST['mobile']
        prdtrn.Status = 'InProgress'
        prdtrn.Datecompleted = date.today()
        prdtrn.save()

        cust= prdtrn.user.first_name
        cart = Transact_dtl.objects.filter(Transact_id=prdtrn)
        

        # mailing login
        subject = 'Order No. ' + str(cart_id) + ' placed successfully'
        
        usr= request.user
        ap_email = usr.email  

        from_email = settings.EMAIL_HOST_USER
        to_list = [settings.EMAIL_HOST_USER, ap_email]

        #image_path = 'C:\Python\Artique\ArtiqueApp\static\images\Artique.jpg'
        image_path = settings.MEDIA_ROOT + '\ArtiqueApp\static\images\Artique.jpg'
        image_path1 = settings.MEDIA_ROOT + '\ArtiqueApp\static\images\Art_Attach.jpg'
        image_name = Path(image_path).name

ArtiqueApp/templates/Appointment.html
{% extends 'Base.html' %}

{% block content%}

{% load static %}

<!-- contact -->
  <section class="container-fluid mt-5 p-5 customers">

   <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="well-block">
                        <div class="well-title text-warning">
                            <h2>Book an Appointment</h2>
                        </div>
                        <form method="POST" action = "{% url 'confirmappoint' %}">
                        {% csrf_token %}
                            <!-- Form start -->
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label" for="name">Name</label>
                                        <input id="name" name="name" type="text" placeholder="Name" class="form-control input-md" value={{ ap_name }}>
                                    </div>
                                </div>
                                <!-- Text input-->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label" for="emailid">Email</label>
                                        <input id="emailid" name="emailid" type="text" placeholder="E-Mail" class="form-control input-md" value={{ ap_email }}>
                                    </div>
                                </div>


                                <!-- Text input-->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label" for="dt">Preferred Date</label>
                                        <input id="dt" name="dt" type="date" placeholder="Preferred Date" class="form-control input-md">
                                    </div>
                                </div>
                                <!-- Select Basic -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label" for="visit_time">Preferred Time</label>
                                        <select id="visit_time" name="visit_time" class="form-control">
                                            <option value="10:00 to 10:30">10:00 to 10:30</option>
                                            <option value="11:00 to 11:30">11:00 to 11:30</option>
                                            <option value="12:00 to 12:30">12:00 to 12:30</option>
                                            <option value="13:00 to 13:30">13:00 to 13:30</option>
                                            <option value="18:00 to 18:30">18:00 to 18:30</option>
                                            <option value="19:00 to 19:30">19:00 to 19:30</option>
                                            <option value="20:00 to 20:30">20:00 to 20:30</option>
                                            <option value="21:00 to 21:30">21:00 to 21:30</option>                                            
                                        </select>
                                    </div>
                                </div>

                                 <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label" for="mobile">Mobile No.</label>
                                        <input id="mobile" name="mobile" type="text" placeholder="Mobile No." class="form-control input-md" value={{ ap_mob }}>
                                    </div>
                                </div>

                                <!-- Select Basic -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label" for="typ">Appointment For</label>
                                        <select id="typ" name="typ" class="form-control">
                                            <option value="Tailoring">Tailoring</option>
                                            <option value="Designer Service">Designer Service</option>
                                            <option value="Buy Artique Collection">Buy Artique Collection</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label" for="msg">Comments</label>
                                        <input id="msg" name="msg" type="textarea"  
                                                        rows="5" 
                                                        style="height:100px;"
                                                        placeholder="Message" class="form-control input-md">
                                      
                                    </div>
                                </div>

                                <!-- Button -->
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <button id="singlebutton" name="singlebutton" class="btn btn-success">Make An Appointment</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- form end -->
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="well-block">
                   
                        <div class="feature-block">
                            <div class="feature feature-blurb-text">
                                <h4 class="feature-title text-warning">Book an Appointment</h4>
                                <div class="feature-content">
                                    <p class="text-muted">Book yourself an appointment online. Choose your date and time & our designer will be there to help you out.</p>
                                </div>
                            </div>
                            <div class="feature feature-blurb-text">
                                <h4 class="feature-title text-warning">Customization & Measurements</h4>
                                <div class="feature-content">
                                    <p class="text-muted">Our designer will help you to come up with look that suits you best and also she will show you fabric swatches if you need more fabric. Designer will take your measurements to ensure that you get perfect tailored fit. </p>
                                </div>
                            </div>
                            <div class="feature feature-blurb-text">
                                <h4 class="feature-title text-warning">Deliver at your Doorstep</h4>
                                <div class="feature-content">
                                    <p class="text-muted">All that's left is for you to complete the payment, hand over your fabric and leave the rest to us. We'll get working on your custom clothing and it will be at your door as per your delivery schedule.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </section>
  <!-- end of contact -->







      <!-- end of Team -->
<!--footer-->

  <footer>
        <div class="container-fluid">
          <div class="row">
           
            <div class="col text-center">
                    <h1 class="text-warning font-weight-bold text-capitalize p-3">Artique Fashion Boutique LLC</h1>
                    <h4 class="text-secondary font-weight-light font-italic mb-3">Shop No. 4, Bldg. No. 37, Behind Al Dhafra International School</h4>
                    <h4 class="text-secondary font-weight-light font-italic mb-3">Shabia 9, Musaffah, Abu Dhabi, UAE</h4>
                    <div class="py-2">
                        <i class="fa fa-phone fa-2x " aria-hidden="true"></i>0562582868
                      <a href="https://www.facebook.com/ArtiqueFashions"><i class="fab fa-facebook-square fa-2x text-primary mx-3"></i></a>                       
                        
                        <a href="https://www.instagram.com/artique_fashion"><i class="fab fa-instagram fa-2x text-danger mx-3"></i></a>
                    </div>
                    <p class="text-light py-4 m-0">&copy;Copyright 2018 - Made by CodeAndCreate</p>                
            </div>
          
        </div>
  </footer>
<!--end of footer-->


 
{% endblock%}







 
        

ArtiqueApp/templates/Artiquehome.html
Hi....

ArtiqueApp/templates/Gallery.html
{% extends 'Base.html' %}

{% block content%}

{% load static %}



<!-- Gallery -->
  <section class="gallery p-5">
      <div class="container">
        <!-- title -->
        <div class="row">
          <div class="col text-center py-5">
            <h1 class="text-secondary font-italic common-title">Collections</h1>
          </div>
        </div>
        <!-- end of title -->
      </div>
    </section>
  <!-- end of Gallery -->







      <!-- end of Team -->


<!--footer-->

  <footer>
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <h1 class="text-primary font-weight-bold text-capitalize p-3">Artique Fashion Boutique LLC</h1>
                    <h4 class="text-secondary font-weight-light font-italic mb-3">Shop No. 4, Bldg. No. 37, Behind Al Dhafra International School</h4>
                    <h4 class="text-secondary font-weight-light font-italic mb-3">Shabia 9, Musaffah, Abu Dhabi, UAE</h4>
                    <div class="py-2">
                        <i class="fa fa-phone fa-2x " aria-hidden="true"></i>0562582868
                       <a href="https://www.facebook.com/ArtiqueFashions"><i class="fab fa-facebook-square fa-2x text-primary mx-3"></i></a>                       
                        
                        <a href="https://www.instagram.com/artique_fashion"><i class="fab fa-instagram fa-2x text-danger mx-3"></i></a>
                    </div>
                    <p class="text-light py-4 m-0">&copy;Copyright 2018 - Made by CodeAndCreate</p>
                </div>
            </div>
        </div>
     </footer>
<!--end of footer-->


{% endblock%}

ArtiqueApp/templates/myactivities.html
{% extends 'Base.html' %}

{% block content%}

{% load static %}

<!-- contact -->
  <section class="container-fluid mt-5 p-5 customers">


  
        <div class="container">
            <div class="container-fluid">
                <!-- title -->
                <div class="row">
                    <div class="col text-center py-3">
                       <!-- <h1 class="text-secondary font-italic common-title">Order <span class="text-secondary font-italic common-title"> History</span></h1> -->
                        {% if CartH.count > 0 %}
                            <h1 class="text-warning display-1">Order History</h1>
                        {% endif %}
                    </div>
                </div>
                <!-- end of title -->
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="main-timeline4">

                    {% for CartH in CartH %}

                        <div class="timeline">
                            <a href="#" class="timeline-content">
                                <span class="year">{{ CartH.id }}</span>
                                <div class="inner-content">
                                    <h1 class="title" >Order placed on {{CartH.Datecompleted|date:"D d M Y"}}  for AED {{ CartH.Amount }}</h1>
                                        {{ CartH.Transact_dtl_set.all }}
                                        {% for detail in CartH.transact_dtl_set.all %}
               
                                            <p class="description">
                                                     {{ detail.Product.title }}  for AED {{ detail.Product.Current_Rate }} 
                                            </p>    

                                        {% endfor %} 
                                    <p class="description">
                                        <B>Status : {{ CartH.Status }}</B>
                                    </p>
                                </div>
                            </a>
                        </div>
                    
                    {% endfor %}
                    
                    </div>
                </div>
            </div>
        </div>
        <hr>
        

<div class="container">
            <div class="container-fluid">
                <!-- title -->
                <div class="row">
                    <div class="col text-center py-3">
                        <!--<h1 class="text-secondary font-italic common-title">Appointment <span class="text-secondary font-italic common-title"> History</span></h1> -->
                        {% if Appnt.count > 0 %}
                            <h1 class="text-warning display-1">Appointment History</h1>
                        {% endif %}
                    </div>
                </div>
                <!-- end of title -->
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="main-timeline4">

                    {% for Appnt in Appnt %}

                        <div class="timeline">
                            <a href="#" class="timeline-content">
                                <span class="year">{{Appnt.dt|date:"Y"}}</span>
                                <div class="inner-content">
                                    <h1 class="title" >Appointment Details:</h1>
                                        <p class="description">
                                                Date: {{Appnt.dt|date:"D d M Y"}}
                                        </p>    
                                        <p class="description">
                                                Time: {{Appnt.visit_time}}
                                        </p> 
                                        <p class="description">
                                                Service : {{Appnt.typ}}
                                        </p> 
                                        <p class="description">
                                                Message: {{Appnt.msg}}
                                        </p> 
                                   
                                </div>
                            </a>
                        </div>
                    
                    {% endfor %}
                    
                    </div>
                </div>
            </div>



        </div>
        <hr>
        
  </section>
  <!-- end of contact -->







      <!-- end of Team -->
<!--footer-->

  <footer>
        <div class="container-fluid">
          <div class="row">
           
            <div class="col text-center">
                    <h1 class="text-warning font-weight-bold text-capitalize p-3">Artique Fashion Boutique LLC</h1>
                    <h4 class="text-secondary font-weight-light font-italic mb-3">Shop No. 4, Bldg. No. 37, Behind Al Dhafra International School</h4>
                    <h4 class="text-secondary font-weight-light font-italic mb-3">Shabia 9, Musaffah, Abu Dhabi, UAE</h4>
                    <div class="py-2">
                        <i class="fa fa-phone fa-2x " aria-hidden="true"></i>0562582868
                        <a href="https://www.facebook.com/ArtiqueFashions"><i class="fab fa-facebook-square fa-2x text-primary mx-3"></i></a>                       
                        
                        <a href="https://www.instagram.com/artique_fashion"><i class="fab fa-instagram fa-2x text-danger mx-3"></i></a>
                    </div>
                    <p class="text-light py-4 m-0">&copy;Copyright 2018 - Made by CodeAndCreate</p>                
            </div>
          
        </div>
  </footer>
<!--end of footer-->


 
{% endblock%}







 
        